### PR TITLE
Added new sections to Dryville_story.md

### PR DESCRIPTION
**Pull request by He1a1eh**
#1. Added "Getting Water to Your Homes" as the third section.
#2. Added "Dryville's First Water Works" as the fourth section.

### CODE REVIEW

**Review by abnerbog — APPROVED** [review]
You're all set to move on to the next step!

**Comment by He1a1eh** [comment]
Hi Abner,

Thank you very much for approving my changes! I have just completed step 9, where I closed the loop between the origin repository and my local copy. Could you please confirm when I am ready to move on to the next step?

Thanks,
Helaleh

**Comment by abnerbog** [comment]
Thanks for the heads up Helaleh -- you are good to keep moving !

**Comment by He1a1eh** [comment]
Thank you very much, Abner!
I have reached step 11, where I should add two new sections.

Thanks,
Helaleh

**Comment by abnerbog** [comment]
Thanks Helaleh ! You are all set to move to the next section.

**Pull request merged**
